version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      - DB_URL=postgresql://postgres:bWFZyEjMNtsptlGAiOZAvUlxnMqeYbZC@shuttle.proxy.rlwy.net:28736/railway
      - LOCAL_PORT=:8088
      - JWT_SECRET=qazwsxedcrfv
    env_file:
      - ./config.env
    volumes:
      - ./config.env:/app/config.env
    restart: unless-stopped
